[features]
seeds = false
[programs.localnet]
crypto_donut = "GPhW8yzphVJyX7XzUhDaKHbWVSviwvKqoxuWLaiAMkAi"
[programs.devnet]
crypto_donut = "GPhW8yzphVJyX7XzUhDaKHbWVSviwvKqoxuWLaiAMkAi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/alexander/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
